server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/theplay
    username: root
    password: epicurean1!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
